const U={
  mchat:'https://samir210-az.github.io/m-chat-r/',
  gobdo:'https://autism-az.vercel.app/',
  qs:'https://samir210-az.github.io/an-qiymetlendirme-sistemi/',
  denver:'https://samir210-az.github.io/goog/',
  denverA:'https://samir210-az.github.io/denever/',
  inkishaf:'https://samir210-az.github.io/TEST/',
  mudaxile:'https://samir210-az.github.io/erken-mudaxile/',
  ttap:'https://samir210-az.github.io/AN/',
  aba:'https://samir210-az.github.io/aba-terapiya/',
  scared:'https://samir210-az.github.io/cbt/',
  cbt1:'https://samir210-az.github.io/Cbt1/',
  ai:'https://ai-test-az.vercel.app',
  ixtisas:'https://ixtisas.vercel.app'
};

const QRUPLAR=[
  {id:'autizm',ad:'Autizm skrininqi və diaqnostikası'},
  {id:'inkishaf',ad:'İnkişaf və erkən müdaxilə'},
  {id:'zeka',ad:'Zəka və koqnitiv qiymətləndirmə'},
  {id:'adaptiv',ad:'Adaptiv, sensor və funksional'},
  {id:'aba',ad:'ABA və davranış'},
  {id:'emosional',ad:'Emosional vəziyyət və CBT'},
  {id:'karyera',ad:'Karyera və ixtisas seçimi'}
];

const TESTLER=[
/* ---------- Autizm ---------- */
{id:'m-chat-r',ad:'M-CHAT-R',alt:'Autizm üçün erkən skrininq anketi',qrup:'autizm',tip:'Skrininq',
 yas:'16–30 aylıq uşaqlar',kim:'Valideyn doldurur, mütəxəssis nəticəni şərh edir',muddet:'5–10 dəqiqə',
 ne:'Kiçik yaşlı uşaqda autizm spektr pozuntusu riskini göstərən davranışları skrininq edir.',
 niye:'Autizm nə qədər tez aşkarlanarsa, müdaxilə o qədər tez başlayır. Anket pediatr və psixoloqa uşağı geniş müayinəyə göndərmək lazım olub-olmadığını göstərir.',
 terkib:['20 maddə, hər biri «bəli» və ya «xeyr» cavabı ilə','Maddələr göz təması, adına cavab, göstərmə jesti, təqlid, birgə diqqət, oyun kimi sahələri əhatə edir','Cavablar uşağın adətən necə davrandığına görə verilir, bir dəfəlik vəziyyətə görə yox'],
 netice:['0–2 bal: aşağı risk. Uşaq 24 aylıq deyilsə təkrar skrininq edilir','3–7 bal: orta risk. M-CHAT-R/F izləmə müsahibəsi aparılır','8–20 bal: yüksək risk. Diaqnostik qiymətləndirməyə yönləndirmə lazımdır'],
 mehdud:'Skrininq alətidir, diaqnoz qoymur. Yüksək bal autizm diaqnozunu təsdiqləmir, aşağı bal da onu tam istisna etmir.',
 linkler:[{t:'Aləti aç',u:U.mchat}]},

{id:'gobdo-2',ad:'GOBDÖ-2',alt:'Gilliam Autizm Qiymətləndirmə Şkalası-2 (Türk uyğunlaşdırması)',qrup:'autizm',tip:'Qiymətləndirmə şkalası',
 yas:'3–23 yaş',kim:'Şəxsi yaxşı tanıyan valideyn, müəllim və ya mütəxəssis',muddet:'10–15 dəqiqə',
 ne:'Müşahidə olunan davranışların nə qədər tez-tez baş verdiyinə görə autizm ehtimalını qiymətləndirir.',
 niye:'Davranış əlamətlərini rəqəmə çevirir və uşağın autizmli qrup içindəki mövqeyini göstərir. Diaqnostik prosesin bir hissəsidir, tək başına qərar vermək üçün istifadə olunmur.',
 terkib:['42 maddə, hər biri 0–3 tezlik şkalası ilə','Üç alt şkala: Stereotip davranışlar (1–14), Ünsiyyət (15–28), Sosial qarşılıqlı əlaqə (29–42)','Valideyn müsahibəsi və klinik tarixçə hissəsi'],
 netice:['Hər alt şkalanın xam balı standart bala çevrilir (orta 10)','Standart ballar cəmindən Autizm pozuntusu indeksi (APİ) alınır: 85 və yuxarı ehtimal çox yüksək, 70–84 ehtimal var, 69 və aşağı ehtimal yoxdur','Müqayisə qrupunda mövqe də göstərilir'],
 mehdud:'Mərkəzdəki versiyada 20 maddənin mətni işçi mətndir, ona görə nəticə təxminidir və rəsmi blankla təsdiqlənməlidir. Alət yalnız PIN ilə açılır.',
 linkler:[{t:'Aləti aç (PIN ilə)',u:U.gobdo}]},

{id:'ados-2',ad:'ADOS-2',alt:'Autizm Diaqnostik Müşahidə Cədvəli, ikinci nəşr',qrup:'autizm',tip:'Diaqnostik',
 yas:'12 aydan böyüklərə qədər',kim:'Xüsusi təlim keçmiş klinik mütəxəssis',muddet:'Təxminən 40–60 dəqiqə',
 ne:'Uşağın ünsiyyət, sosial qarşılıqlı əlaqə, oyun və məhdud təkrarlanan davranışlarını planlaşdırılmış oyun və söhbət tapşırıqları vasitəsilə birbaşa müşahidə edir.',
 niye:'Autizm diaqnozunda ən geniş istifadə olunan standartlaşdırılmış müşahidə alətlərindən biridir. Valideyn məlumatını klinisistin gördüyü real davranışla tamamlayır.',
 terkib:['Modullar yaşa və dil səviyyəsinə görə seçilir: Toddler modulu və 1–4-cü modullar','Hər modulda oyuncaqlar və situasiyalar vasitəsilə aparılan strukturlaşdırılmış tapşırıqlar','Müşahidələr maddələr üzrə 0–3 balla kodlaşdırılır'],
 netice:['Alqoritmə görə ballar cəmlənir və «autizm», «autizm spektri» və ya «spektrdən kənar» təsnifatı alınır','Müqayisəli şiddət balı (CSS) əlamətlərin dərəcəsini yaşa görə müqayisə edir'],
 mehdud:'Lisenziyalı materialdır, yalnız təlim keçmiş mütəxəssis tətbiq edə bilər. Nəticə tək başına diaqnoz qoymur, valideyn müsahibəsi və inkişaf tarixçəsi ilə birlikdə şərh olunur.',
 linkler:[{t:'Qiymətləndirmə sistemini aç',u:U.qs}]},

{id:'adi-r',ad:'ADI-R',alt:'Autizm Diaqnostik Müsahibəsi, yenilənmiş',qrup:'autizm',tip:'Müsahibə',
 yas:'Əqli yaşı ən azı 2 il olan uşaq və böyüklər',kim:'Təlim keçmiş klinik mütəxəssis, cavab verən isə uşağı yaxşı tanıyan valideyn',muddet:'Təxminən 1,5–2,5 saat',
 ne:'Valideynlə strukturlaşdırılmış müsahibə vasitəsilə uşağın inkişaf tarixçəsini və hazırkı davranışını əhatə edir.',
 niye:'Diaqnoz üçün vacib olan suala cavab verir: əlamətlər erkən yaşda olub, yoxsa sonradan çıxıb. ADOS-2 ilə birlikdə tətbiq olunması tövsiyə olunur.',
 terkib:['93 maddəlik müsahibə','Üç sahə: qarşılıqlı sosial əlaqə, ünsiyyət və dil, məhdud və təkrarlanan davranışlar','Əlamətlərin 36 aya qədər başlayıb-başlamadığını soruşan hissə'],
 netice:['Alqoritm sahələr üzrə balları hesablayır və kəsmə həddi ilə müqayisə edir','Nəticə autizm diaqnostik meyarlarına uyğunluğu göstərir'],
 mehdud:'Lisenziyalı materialdır. Valideynin xatırlamasına əsaslandığı üçün xatirə təhrifi ola bilər, buna görə ADOS-2 və klinik müşahidə ilə birlikdə istifadə edilir.',
 linkler:[{t:'Qiymətləndirmə sistemini aç',u:U.qs}]},

/* ---------- İnkişaf ---------- */
{id:'denver-ii',ad:'Denver II',alt:'Denver İnkişaf Skrininq Testi',qrup:'inkishaf',tip:'Skrininq',
 yas:'Doğuşdan 6 yaşa qədər',kim:'Psixoloq, pediatr və ya təlim keçmiş mütəxəssis',muddet:'15–20 dəqiqə',
 ne:'Uşağın motor, nitq və sosial inkişafının yaşına uyğun olub-olmadığını yoxlayır.',
 niye:'İnkişaf gecikməsini erkən aşkarlamaq və geniş qiymətləndirməyə yönləndirmək üçündür. Uşağı normal inkişaf edən həmyaşıdları ilə müqayisə edir.',
 terkib:['Təxminən 125 tapşırıq','Dörd sahə: sosial-şəxsi, incə motorika və adaptiv, nitq, iri motorika','Hər tapşırıq üçün yaş zolağı göstərilir, uşaq yaş xəttinə görə qiymətləndirilir'],
 netice:['Hər maddə «keçdi», «keçmədi», «imtina» və ya «fürsət olmadı» kimi qeyd olunur','Nəticə «normal», «ehtiyatlı» və ya «gecikmiş» olaraq təsnif edilir, ehtiyatlı və gecikmiş nəticələr təkrar yoxlanır və ya yönləndirilir'],
 mehdud:'Skrininq alətidir, diaqnoz qoymur və zəka testi deyil. Vaxtından əvvəl doğulmuş uşaqlarda yaş düzəlişi lazımdır.',
 linkler:[{t:'Aləti aç',u:U.denver},{t:'Arxiv',u:U.denverA}]},

{id:'erken-inkishaf',ad:'Erkən İnkişaf qiymətləndirməsi',alt:'Mərkəzin strukturlaşdırılmış dəyərləndirmə aləti',qrup:'inkishaf',tip:'Qiymətləndirmə',
 yas:'Erkən inkişaf yaşındakı uşaqlar',kim:'Mərkəzin mütəxəssisi',muddet:'Uşağa görə dəyişir',
 ne:'Uşağın ümumi inkişaf profilini və mütəxəssisin tövsiyələrini bir yerdə toplayır.',
 niye:'Xüsusi qayğıya ehtiyacı olan uşaqları struktur üzrə dəyərləndirmək və lazım olan reabilitasiya istiqamətini müəyyənləşdirmək üçün hazırlanıb.',
 terkib:['Uşaq məlumatları (kod, yaş, cins) və tarix','Qısa anamnez və valideyn şikayəti','İnkişaf profili və tövsiyələr','Keçirilmiş testlərin qeydi'],
 netice:['Nəticə inkişaf profili və yazılı tövsiyələr şəklində verilir'],
 mehdud:'Standartlaşdırılmış test deyil. Aləti açıq şəkildə reabilitasiya mərkəzinə istiqamətləndirmə məqsədi daşıyır və diaqnostik alətləri əvəz etmir.',
 linkler:[{t:'Aləti aç',u:U.inkishaf}]},

{id:'erken-mudaxile',ad:'Erkən Müdaxilə platforması',alt:'İnkişaf skrininqi (v2) və izləmə',qrup:'inkishaf',tip:'Skrininq və izləmə',
 yas:'Xüsusi qayğıya ehtiyacı olan müxtəlif yaşlı uşaqlar',kim:'Valideyn və mütəxəssis',muddet:'Uşağa görə dəyişir',
 ne:'İnkişaf skrininqini keçirir və nəticələri zaman üzrə izləməyə imkan verir.',
 niye:'Bir dəfəlik nəticə yox, uşağın inkişafının dəyişməsini göstərmək üçündür. Valideyn və mütəxəssis eyni uşaq profilinə baxır.',
 terkib:['Uşaq profilləri (doğum tarixi və demoqrafik məlumat)','İnkişaf skrininqi (v2) anketi','Skrininq tarixçəsi','Məqsəd kitabxanası'],
 netice:['Nəticələr tarixçədə saxlanır, sahələr üzrə ətraflı təhlil isə ayrıca açılır'],
 mehdud:'Skrininq nəticəsi diaqnoz deyil. Anketin dəqiq maddə sayı və hesablama qaydası bu kataloqda göstərilmir.',
 linkler:[{t:'Aləti aç',u:U.mudaxile}]},

/* ---------- Zəka ---------- */
{id:'wisc-v',ad:'WISC-V',alt:'Wechsler Uşaq Zəka Şkalası, beşinci nəşr',qrup:'zeka',tip:'Diaqnostik (IQ)',
 yas:'6–16 yaş 11 ay',kim:'Lisenziyalı psixoloq',muddet:'Təxminən 60–80 dəqiqə',
 ne:'Uşağın ümumi zehni qabiliyyətini (IQ) və onun hansı sahələrdən ibarət olduğunu ölçür.',
 niye:'Öyrənmə çətinliyi, zehni gerilik, istedad və ya diqqət problemi şübhəsi olanda uşağın güclü və zəif tərəflərini müəyyənləşdirmək üçün istifadə olunur.',
 terkib:['Ümumilikdə 15 subtest, əsas profil üçün 10-u tətbiq olunur','Beş əsas indeks: şifahi anlama, vizual-məkan, mayeli məntiq, işçi yaddaş, emal sürəti','Subtestlər arasında söz ehtiyatı, bloklarla dizayn, matris, rəqəm təkrarı, kodlaşdırma kimi tapşırıqlar'],
 netice:['Tam miqyas IQ (FSIQ) və beş indeks balı alınır, orta 100, standart kənarlaşma 15','Ballar yaş normasına görə təsnif edilir (aşağı, orta, yuxarı və s.)','İndekslər arasındakı fərq uşağın profilini göstərir'],
 mehdud:'Yalnız lisenziyalı psixoloq tətbiq edə bilər. Bir test nəticəsi uşağın bütün imkanlarını göstərmir, nitqi çox məhdud və ya qeyri-şifahi uşaqlarda nəticə təhrif oluna bilər.',
 linkler:[{t:'Qiymətləndirmə sistemini aç',u:U.qs}]},

{id:'leiter-3',ad:'Leiter-3',alt:'Leiter beynəlxalq performans şkalası, üçüncü nəşr',qrup:'zeka',tip:'Diaqnostik (IQ)',
 yas:'3–75 yaş',kim:'Lisenziyalı psixoloq',muddet:'Təxminən 30–45 dəqiqə',
 ne:'Nitqdən asılı olmayan qeyri-şifahi zəkanı və diqqət, yaddaş funksiyalarını ölçür.',
 niye:'Nitqi inkişaf etməyən, autizmli, eşitmə çətinliyi olan və ya Azərbaycan dilini bilməyən uşaqlarda şifahi testlər imkan vermir. Leiter-3 təlimatı jestlə verilir və cavab verilmək üçün danışmaq tələb olunmur.',
 terkib:['Vizuallaşdırma və məntiq bölməsi: formaları tapmaq, tamamlamaq, təsnif etmək, ardıcıllıq','Diqqət və yaddaş bölməsi: davamlı diqqət, irəli və əks yaddaş','Uşaq yaşına görə uyğun subtestlər seçilir'],
 netice:['Qeyri-şifahi IQ balı, orta 100','Diqqət və yaddaş üzrə ayrıca bal'],
 mehdud:'Lisenziyalı materialdır. Qeyri-şifahi IQ şifahi və akademik bacarıqları əhatə etmir, buna görə WISC-V və ya digər qiymətləndirmələrlə tamamlanmalıdır.',
 linkler:[{t:'Qiymətləndirmə sistemini aç',u:U.qs}]},

/* ---------- Adaptiv ---------- */
{id:'vineland-3',ad:'Vineland-3',alt:'Vineland adaptiv davranış şkalası, üçüncü nəşr',qrup:'adaptiv',tip:'Qiymətləndirmə (müsahibə və anket)',
 yas:'Doğuşdan 90 yaşa qədər',kim:'Psixoloq valideynlə müsahibə aparır və ya valideyn, müəllim anket doldurur',muddet:'20–60 dəqiqə',
 ne:'Uşağın gündəlik həyatda real olaraq nə bacardığını ölçür: ünsiyyət, özünə xidmət, sosial münasibət və hərəkət.',
 niye:'IQ uşağın potensialını, Vineland isə gündəlik müstəqilliyini göstərir. Əlillik dərəcəsinin təyinində, müdaxilə planında və reabilitasiyanın nəticəsini izləməkdə istifadə olunur.',
 terkib:['Üç əsas sahə: ünsiyyət, gündəlik həyat bacarıqları, sosiallaşma','Motor bacarıqlar sahəsi kiçik yaşda tətbiq olunur','İstəyə bağlı: uyğunsuz davranış sahəsi'],
 netice:['Hər sahə və ümumi adaptiv davranış kompoziti üçün standart bal (orta 100)','Yaş ekvivalentləri və güclü, zəif tərəflərin profili'],
 mehdud:'Cavab verənin məlumatına əsaslanır, ona görə cavab verən şəxsin uşağı nə qədər yaxşı tanıması vacibdir. Lisenziyalı materialdır.',
 linkler:[{t:'Qiymətləndirmə sistemini aç',u:U.qs},{t:'ABA platforması',u:U.aba}]},

{id:'sensory-profile-2',ad:'Sensory Profile 2',alt:'Sensor profil, ikinci nəşr',qrup:'adaptiv',tip:'Anket',
 yas:'Doğuşdan 14 yaş 11 aya qədər (yaşa görə ayrı formalar)',kim:'Valideyn və ya müəllim doldurur, ergoterapevt və ya psixoloq şərh edir',muddet:'10–20 dəqiqə',
 ne:'Uşağın səs, işıq, toxunuş, hərəkət və digər hisslərə gündəlik reaksiyasını qiymətləndirir.',
 niye:'Bəzi uşaqlar səs-küydən, geyim etiketindən, qida teksturasından həddindən artıq narahat olur, bəziləri isə ağrı, temperatur və ya hərəkəti az hiss edir. Alət bu fərqlərin davranışa təsirini göstərir.',
 terkib:['Yaşa görə infant, toddler, child formaları və qısa forma','Sensor sistemlər: eşitmə, görmə, toxunma, hərəkət, bədən mövqeyi, oral','Davranış nümunələri: sensor axtarışı, sensor qaçınma, sensor həssaslıq, sensor qeydiyyatsızlıq (dörd kvadrant)'],
 netice:['Hər kvadrant və sistem üçün bal «həmyaşıdlarına nisbətən çox az»dan «çox çox»a qədər təsnif edilir'],
 mehdud:'Anket valideynin müşahidəsinə əsaslanır və diaqnoz qoymur. Nəticə ergoterapiya planının əsası ola bilər, lakin klinik müşahidə ilə təsdiqlənməlidir.',
 linkler:[{t:'Qiymətləndirmə sistemini aç',u:U.qs}]},

{id:'ttap',ad:'TTAP',alt:'Keçid və peşə yönümlü qiymətləndirmə profili',qrup:'adaptiv',tip:'Qiymətləndirmə',
 yas:'Yeniyetmə və böyüklər (TTAP əsasən autizmli gənclər üçün işlənib)',kim:'Mütəxəssis müşahidə və müsahibə ilə',muddet:'Fərdi, bir neçə görüşə yayıla bilər',
 ne:'Gəncin müstəqil yaşamaq və işləmək üçün hansı bacarıqlara malik olduğunu çoxsahəli şəkildə qiymətləndirir.',
 niye:'Məktəbi bitirən və ya yetkinliyə keçən gənc üçün real hədəflər qoymaq, işə hazırlıq və gündəlik müstəqillik planı hazırlamaq üçündür.',
 terkib:['Mərkəzin platformasında sahələr: iş bacarıqları, sosial-emosional, koqnitiv, gündəlik fəaliyyət, sensor-motor koordinasiya, nitq-dil','Yeni pasiyent əlavə etmək, tarixə görə test keçirmək, nəticəni saxlamaq','Əvvəlki testlərə baxış: bal, səviyyə, güclü tərəflər, hesabatlar'],
 netice:['Hər sahə üzrə bal, səviyyə və güclü tərəflər göstərilir'],
 mehdud:'Mərkəzin elektron versiyasında sahə adları orijinal TTAP-dan fərqlənə bilər, bu kataloq yalnız platformadakı göstərilən strukturu təsvir edir.',
 linkler:[{t:'Aləti aç',u:U.ttap}]},

/* ---------- ABA ---------- */
{id:'vb-mapp',ad:'VB-MAPP',alt:'Şifahi davranış mərhələlərinin qiymətləndirilməsi və yerləşdirmə proqramı',qrup:'aba',tip:'Qiymətləndirmə',
 yas:'Normal inkişafda 0–48 ay səviyyəsi (autizmli və ya nitq gecikməsi olan uşaqlar üçün)',kim:'ABA mütəxəssisi (BCBA və ya təlim keçmiş terapevt)',muddet:'Bir neçə seans',
 ne:'Uşağın dil, öyrənmə və sosial bacarıqlarını Skinnerin şifahi davranış təhlilinə əsasən qiymətləndirir.',
 niye:'ABA proqramı üçün başlanğıc nöqtəni təyin edir, hədəfləri seçir və irəliləyişi izləyir.',
 terkib:['170 mərhələ, 16 sahə: tələb, adlandırma, dinləyici reaksiyası, təqlid, oyun, sosial bacarıq, oxu, yazı, riyaziyyat və s.','Üç səviyyə: 0–18, 18–30, 30–48 ay','Əngəllər qiymətləndirməsi (24 əngəl) və keçid qiymətləndirməsi'],
 netice:['Hər mərhələ 0, ½ və ya 1 balla qeyd olunur','Profil uşağın hansı səviyyədə olduğunu və hansı əngəllərin öyrənməyə mane olduğunu göstərir'],
 mehdud:'Normal inkişaf mərhələlərinə əsaslandığı üçün bütün uşaqlar üçün tam uyğun olmaya bilər. Alət özü müalicə deyil, plan üçün əsasdır.',
 linkler:[{t:'ABA platformasını aç',u:U.aba}]},

{id:'ablls-r',ad:'ABLLS-R',alt:'Əsas dil və öyrənmə bacarıqlarının qiymətləndirilməsi, yenilənmiş',qrup:'aba',tip:'Qiymətləndirmə',
 yas:'Əsasən kiçik yaşlı və inkişaf gecikməsi olan uşaqlar',kim:'ABA mütəxəssisi',muddet:'Bir neçə seans',
 ne:'Uşağın dil, akademik, özünəxidmət və motor bacarıqlarını geniş siyahı üzrə izləyir.',
 niye:'Hansı bacarığın var, hansının yoxdur sualına konkret cavab verir və tədris proqramı üçün hədəf siyahısı yaradır.',
 terkib:['544 bacarıq, 25 sahə: əməkdaşlıq, vizual qavrama, dil, təqlid, oyun, sosial, motor, özünəxidmət və s.','Bacarıq izləmə cədvəli (grid) və tapşırıq təhlili'],
 netice:['Bacarıqlar cədvəldə rənglənir, yeni nailiyyətlər tarix üzrə izlənir'],
 mehdud:'Standart bal vermir, norm cədvəli yoxdur. Əsas məqsəd müqayisə yox, fərdi proqram və izləmədir.',
 linkler:[{t:'ABA platformasını aç',u:U.aba}]},

{id:'afls',ad:'AFLS',alt:'Funksional həyat bacarıqlarının qiymətləndirilməsi',qrup:'aba',tip:'Qiymətləndirmə',
 yas:'Uşaqdan böyüklərə qədər',kim:'ABA mütəxəssisi, müəllim, valideyn',muddet:'Seçilmiş modullara görə dəyişir',
 ne:'Gündəlik həyatda müstəqil işləmək üçün lazım olan bacarıqları qiymətləndirir.',
 niye:'Təhsil bitəndən sonra da lazım olan real həyat bacarıqlarını ön plana çəkir və uyğun tədris hədəfləri verir.',
 terkib:['Altı modul: əsas həyat bacarıqları, ev bacarıqları, cəmiyyətdə iştirak, məktəb bacarıqları, peşə bacarıqları, müstəqil yaşayış','Hər modul bacarıq siyahısı və qiymətləndirmə cədvəlindən ibarətdir'],
 netice:['Bacarıqlar üzrə qiymət cədvəli və hədəf siyahısı'],
 mehdud:'Norm əsaslı test deyil, standart bal vermir. Hədəflərin seçimi mütəxəssisin klinik qərarına bağlıdır.',
 linkler:[{t:'ABA platformasını aç',u:U.aba}]},

{id:'fba',ad:'FBA',alt:'Funksional davranış qiymətləndirməsi',qrup:'aba',tip:'Qiymətləndirmə üsulu',
 yas:'Bütün yaşlar',kim:'Davranış analitiki, psixoloq',muddet:'Bir neçə gün və ya həftə',
 ne:'Problem davranışın nə üçün baş verdiyini, yəni funksiyasını müəyyən edir.',
 niye:'Aqressiya, özünə zərər, qışqırıq kimi davranışlar müxtəlif səbəblərdən ola bilər. Müdaxilə səbəbə yönəlməsə, davranış artıb davam edə bilər.',
 terkib:['Dolayı üsullar: valideyn və müəllimlə müsahibə, sorğu vərəqləri','Birbaşa müşahidə: A-B-C qeydləri (nə oldu, uşaq nə etdi, sonra nə baş verdi)','Lazım olduqda nəzarət olunan funksional analiz'],
 netice:['Davranışın funksiyası ehtimalı: diqqət almaq, tapşırıqdan qaçmaq, istədiyini əldə etmək və ya avtomatik (sensor) qazanc','Nəticəyə görə davranış dəstək planı hazırlanır'],
 mehdud:'FBA hazır test deyil, proses və üsullar toplusudur. Düzgün aparılması üçün təlim keçmiş mütəxəssis və kifayət qədər müşahidə vaxtı lazımdır.',
 linkler:[{t:'ABA platformasını aç',u:U.aba}]},

{id:'peak',ad:'PEAK',alt:'Qabaqcıl biliyin ortaya çıxmasına dəstək proqramı',qrup:'aba',tip:'Qiymətləndirmə və proqram',
 yas:'Uşaqlardan böyüklərə qədər',kim:'ABA mütəxəssisi',muddet:'Modula görə dəyişir',
 ne:'Dil və öyrənmə bacarıqlarını əlaqələr çərçivəsi nəzəriyyəsinə əsaslanaraq qiymətləndirir.',
 niye:'Uşağın sadə təqlid etməkdən mücərrəd və fikri əlaqələr qurmağa keçməsinə kömək edən hədəfləri seçmək üçün istifadə olunur.',
 terkib:['Dörd modul: birbaşa təlim, ümumiləşdirmə, ekvivalentlik, transformasiya','Hər modulda bacarıqlar sırası və qiymətləndirmə'],
 netice:['Modullar üzrə bal və növbəti hədəflərin siyahısı'],
 mehdud:'Alətin açılışı bəzi mənbələrdə fərqli yazılır, rəsmi ad Promoting the Emergence of Advanced Knowledge-dır. Klinik təcrübədə VB-MAPP və ABLLS-R qədər geniş yayılmayıb.',
 linkler:[{t:'ABA platformasını aç',u:U.aba}]},

/* ---------- Emosional ---------- */
{id:'scared',ad:'SCARED',alt:'Uşaqlarda narahatlıqla bağlı emosional pozuntuların skrininqi',qrup:'emosional',tip:'Anket',
 yas:'8–18 yaş (valideyn forması bütün yaşlar üçün)',kim:'Uşaq və valideyn ayrıca doldurur, psixoloq şərh edir',muddet:'10–15 dəqiqə',
 ne:'Uşaq və yeniyetmələrdə narahatlıq pozuntusu əlamətlərini skrininq edir.',
 niye:'Narahatlıq çox vaxt xəbərdarlıq edilmədən gizli qalır: uşaq qarın ağrısı, məktəbdən imtina və ya yapışqanlıq kimi göründürür. Anket hansı növ narahatlığın üstünlük təşkil etdiyini göstərir.',
 terkib:['41 maddə, uşaq forması (SCARED-C) və valideyn forması (SCARED-P)','Hər maddə 0–2 şkalası ilə: doğru deyil, bəzən doğrudur, çox doğrudur','Beş alt şkala: panik və somatik, ümumi narahatlıq, ayrılıq narahatlığı, sosial narahatlıq, məktəbdən qaçınma'],
 netice:['Ümumi bal 25 və yuxarıdırsa narahatlıq pozuntusu ehtimalı yüksəkdir','Alt şkalalar üçün ayrı kəsmə həddi var: panik/somatik 7, ümumi narahatlıq 9, ayrılıq 5, sosial 8, məktəbdən qaçınma 3'],
 mehdud:'Skrininq alətidir, diaqnoz qoymur. Nəticə klinik müsahibə ilə birlikdə şərh edilir. Uşaq və valideyn cavabları bir-birindən fərqli ola bilər, bu da məlumatdır.',
 linkler:[{t:'Aləti aç',u:U.scared}]},

{id:'cbt-klinik',ad:'CBT Klinik Qiymətləndirmə',alt:'Valideyn, uşaq və müəllim anketləri',qrup:'emosional',tip:'Anket',
 yas:'Uşaqlar və yeniyetmələr',kim:'Valideyn, uşaq və müəllim ayrıca doldurur, psixoloq şərh edir',muddet:'Hər forma 5–10 dəqiqə',
 ne:'Narahatlıq, emosiyanın idarə olunması, sosial bacarıqlar, davranış və gündəlik fəaliyyəti koqnitiv davranış terapiyası nöqteyi-nəzərindən qiymətləndirir.',
 niye:'Müxtəlif mühitdə (ev, məktəb, uşağın öz baxışı) toplanmış məlumat CBT planı üçün hansı sahədən başlamaq lazım olduğunu göstərir.',
 terkib:['Valideyn forması (20 maddə), uşaq forması (20 maddə), müəllim forması (10 maddə)','0–4 Likert şkalası, «heç vaxt»dan «həmişə»yə','Beş sahə: narahatlıq (A), emosiya tənzimi (E), sosial bacarıq (S), davranış (B), gündəlik fəaliyyət (D)'],
 netice:['Nəticə faizlə göstərilir: 0–40% normal diapazon, 41–70% subklinik risk, 71–100% yüksək klinik əhəmiyyət','Hər sahə üzrə ayrıca nəticə və CBT tövsiyəsi'],
 mehdud:'Skrininq və istiqamət alətidir, diaqnoz qoymur. Faiz hədləri mərkəzin tətbiq etdiyi şərh qaydasıdır. Hesablama düyməsi lisenziya tələb edir.',
 linkler:[{t:'Aləti aç',u:U.cbt1}]},

{id:'phq-9',ad:'PHQ-9',alt:'Pasiyent sağlamlıq anketi, depressiya',qrup:'emosional',tip:'Anket',
 yas:'Yeniyetmə və böyüklər',kim:'Özünü qiymətləndirmə, psixoloq və ya həkim şərh edir',muddet:'2–5 dəqiqə',
 ne:'Son iki həftədəki depressiya əlamətlərinin sayını və şiddətini ölçür.',
 niye:'Depressiyanı skrininq etmək, müalicənin təsirini izləmək üçün qısa və tez istifadə olunan alətdir.',
 terkib:['9 maddə, hər biri depressiyanın bir əlamətinə uyğundur: əhval, maraq itkisi, yuxu, yorğunluq, iştah, özünə dəyər, diqqət, hərəkət, ölüm və ya özünə zərər fikirləri','Hər maddə 0–3 balla qiymətləndirilir'],
 netice:['Ümumi bal 0–27','5–9: yüngül, 10–14: orta, 15–19: orta-ağır, 20–27: ağır','9-cu maddə (özünə zərər fikirləri) sıfırdan fərqlidirsə ayrıca klinik qiymətləndirmə lazımdır'],
 mehdud:'Skrininq alətidir, diaqnoz qoymur. Cavablar şüurlu şəkildə yüngülləşdirilə və ya şişirdilə bilər.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'bdi-ii',ad:'BDI-II',alt:'Bek depressiya siyahısı, ikinci nəşr',qrup:'emosional',tip:'Anket',
 yas:'13 yaş və yuxarı',kim:'Özünü qiymətləndirmə, psixoloq şərh edir',muddet:'5–10 dəqiqə',
 ne:'Son iki həftədə depressiyanın şiddətini ölçür.',
 niye:'Depressiyanın dərəcəsini təyin etmək və müalicə boyu dəyişikliyi izləmək üçündür.',
 terkib:['21 maddə, hər biri 0–3 şkalası ilə','Emosional, koqnitiv və fiziki əlamətlər: kədər, ümidsizlik, günah hissi, yuxu, iştah, enerji və s.'],
 netice:['Ümumi bal 0–63','0–13: minimal, 14–19: yüngül, 20–28: orta, 29–63: ağır'],
 mehdud:'Skrininq və şiddət ölçüsüdür, diaqnoz qoymur. Özünə zərər fikirlərini soruşan maddə ayrıca diqqət tələb edir. Orijinal testin müəllif hüququ var.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'sds',ad:'SDS',alt:'Zunq özünü qiymətləndirmə depressiya şkalası',qrup:'emosional',tip:'Anket',
 yas:'Böyüklər',kim:'Özünü qiymətləndirmə, mütəxəssis şərh edir',muddet:'5–10 dəqiqə',
 ne:'Depressiv əlamətləri son vaxt üzrə özünü qiymətləndirmə ilə ölçür.',
 niye:'Depressiyanın skrininqi və dəyişikliyin izlənməsi üçün tarixən geniş istifadə olunan qısa anketdir.',
 terkib:['20 maddə, dörd variantlı cavab (heç vaxt, bəzən, tez-tez, həmişə)','Maddələrin yarısı müsbət, yarısı mənfi formulə olunub'],
 netice:['Xam bal 20–80, ümumiyyətlə 80-ə bölünüb indeks kimi göstərilir','Adətən indeks 50-dən aşağı normal, 50–59 yüngül, 60–69 orta, 70 və yuxarı ağır depressiya kimi şərh olunur'],
 mehdud:'Skrininq alətidir, diaqnoz qoymur. Kəsmə həddi mənbələrə görə fərqlənə bilər, ona görə klinik qərar ayrıca verilir.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'gad-7',ad:'GAD-7',alt:'Ümumi narahatlıq pozuntusu şkalası',qrup:'emosional',tip:'Anket',
 yas:'Yeniyetmə və böyüklər',kim:'Özünü qiymətləndirmə, mütəxəssis şərh edir',muddet:'2 dəqiqə',
 ne:'Son iki həftədəki narahatlığın şiddətini ölçür.',
 niye:'Ümumi narahatlıq pozuntusunu skrininq etmək və müalicənin təsirini izləmək üçün tez istifadə edilir.',
 terkib:['7 maddə: əsəbilik, nəzarətsiz narahatlıq, istirahət edə bilməmə, qorxu hissi və s.','Hər maddə 0–3 balla qiymətləndirilir'],
 netice:['Ümumi bal 0–21','5–9: yüngül, 10–14: orta, 15–21: ağır','10 və yuxarı bal əlavə klinik qiymətləndirməyə əsas verir'],
 mehdud:'Skrininq alətidir, narahatlığın səbəbini və ya növünü göstərmir.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'dass-21',ad:'DASS-21',alt:'Depressiya, narahatlıq və stress şkalası',qrup:'emosional',tip:'Anket',
 yas:'Yeniyetmə və böyüklər',kim:'Özünü qiymətləndirmə, mütəxəssis şərh edir',muddet:'5–10 dəqiqə',
 ne:'Son bir həftədə depressiya, narahatlıq və stress əlamətlərini üç ayrı şkala ilə ölçür.',
 niye:'Bu üç vəziyyət tez-tez bir yerdə olur. DASS-21 hansının daha çox çıxdığını göstərir.',
 terkib:['21 maddə, hər şkala üçün 7 maddə','Hər maddə 0–3 balla qiymətləndirilir'],
 netice:['Hər şkalanın cəmi 2-yə vurulur','Hər şkala üçün normal, yüngül, orta, ağır və çox ağır dərəcələr müəyyənləşir'],
 mehdud:'Skrininq alətidir. Cəmləmə qaydasında 2-yə vurmaq lazımdır, bunu unutmaq nəticəni yarıya endirir.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'y-bocs',ad:'Y-BOCS',alt:'Yeyl-Braun obsessiv-kompulsiv şkalası',qrup:'emosional',tip:'Klinik şkala',
 yas:'Uşaq, yeniyetmə və böyüklər (uşaqlar üçün CY-BOCS versiyası var)',kim:'Klinik müsahibə ilə mütəxəssis',muddet:'20–40 dəqiqə',
 ne:'Obsessiv-kompulsiv pozuntunun şiddətini ölçür.',
 niye:'Obsesiya (təkrarlanan narahat fikirlər) və kompulsiya (təkrarlanan hərəkətlər) gündəlik həyata nə qədər mane olur sualına cavab verir və müalicənin təsirini izləyir.',
 terkib:['Simptomlar siyahısı','10 maddəlik şiddət şkalası: 5 maddə obsesiyalar, 5 maddə kompulsiyalar','Hər maddə 0–4: vaxt, müdaxilə, sıxıntı, müqavimət və nəzarət'],
 netice:['Ümumi bal 0–40','0–7: subklinik, 8–15: yüngül, 16–23: orta, 24–31: ağır, 32–40: çox ağır'],
 mehdud:'Əsli klinik müsahibə şkalasıdır. Özünü qiymətləndirmə variantı müsahibənin yerini tutmur. Diaqnoz üçün ayrıca klinik qiymətləndirmə lazımdır.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'isi',ad:'ISI',alt:'Yuxusuzluğun şiddət indeksi',qrup:'emosional',tip:'Anket',
 yas:'Böyüklər və yeniyetmələr',kim:'Özünü qiymətləndirmə, mütəxəssis şərh edir',muddet:'2–3 dəqiqə',
 ne:'Son iki həftədəki yuxusuzluğun şiddətini və gündəlik həyata təsirini ölçür.',
 niye:'Yuxu pozuntusu depressiya, narahatlıq və diqqət problemlərini ağırlaşdırır. ISI yuxu probleminin klinik əhəmiyyətini göstərir.',
 terkib:['7 maddə: yuxuya getmə, yuxunu saxlama, erkən oyanma, razılıq, gündəlik fəaliyyətə təsiri, narahatlıq','Hər maddə 0–4 şkalası ilə'],
 netice:['Ümumi bal 0–28','0–7: yuxusuzluq yoxdur, 8–14: eşik həddindən aşağı, 15–21: orta, 22–28: ağır'],
 mehdud:'Skrininq və şiddət ölçüsüdür. Yuxu pozuntusunun səbəbini (tibbi, psixoloji, mühit) göstərmir.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'pss-10',ad:'PSS-10',alt:'Qavranılan stress şkalası',qrup:'emosional',tip:'Anket',
 yas:'Yeniyetmə və böyüklər',kim:'Özünü qiymətləndirmə, mütəxəssis şərh edir',muddet:'3–5 dəqiqə',
 ne:'Son bir ayda həyatın nə qədər nəzarətsiz, gözlənilməz və yüklənmiş qəbul edildiyini ölçür.',
 niye:'Stress hadisənin özündən çox, onun necə qəbul edildiyindən asılıdır. PSS-10 məhz bu qavrayışı ölçür.',
 terkib:['10 maddə, hər biri 0–4 şkalası ilə','Bəzi maddələr tərs hesablanır'],
 netice:['Ümumi bal 0–40, yüksək bal daha çox qavranılan stress deməkdir','Rəsmi klinik kəsmə həddi yoxdur, adətən 0–13 aşağı, 14–26 orta, 27–40 yüksək stress kimi şərh olunur'],
 mehdud:'Diaqnostik alət deyil və kəsmə həddləri şərti hesab olunur. Nəticə qruplar və zaman üzrə müqayisə üçün daha faydalıdır.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

{id:'scl-90',ad:'SCL-90',alt:'Simptomlar siyahısı, 90 maddə',qrup:'emosional',tip:'Anket',
 yas:'Yeniyetmə və böyüklər',kim:'Özünü qiymətləndirmə, psixoloq şərh edir',muddet:'12–20 dəqiqə',
 ne:'Geniş psixoloji simptom spektrini son bir həftə üzrə qiymətləndirir.',
 niye:'Bir dəfəyə bir neçə sahədə şikayətin ümumi mənzərəsini göstərir. Tək bir diaqnozu yoxlamır, hansı sahəyə daha çox diqqət lazım olduğunu göstərir.',
 terkib:['90 maddə, hər biri 0–4 şkalası ilə','Doqquz sahə: somatizasiya, obsessiv-kompulsiv, şəxsiyyətlərarası həssaslıq, depressiya, narahatlıq, düşmənçilik, fobik narahatlıq, paranoid düşüncə, psixotizm'],
 netice:['Hər sahə üzrə orta bal','Ümumi indekslər: GSI (ümumi simptom şiddəti), PST (simptom sayı), PSDI (simptom şiddət indeksi)'],
 mehdud:'Skrininq və simptom profili alətidir, diaqnoz qoymur. Maddə sayının çoxluğu yorğunluq yarada bilər.',
 linkler:[{t:'Anket platformasını aç',u:U.ai}]},

/* ---------- Karyera ---------- */
{id:'ixtisas',ad:'İxtisas seçimi testi',alt:'Maraqlar, qabiliyyət və dəyərlər üzrə test',qrup:'karyera',tip:'Test',
 yas:'14–16 yaşlı yeniyetmələr',kim:'Klinik psixoloq tətbiq edir, nəticəni yalnız psixoloq görür',muddet:'Üç modul üzrə',
 ne:'Yeniyetmənin ixtisas və ali təhsil seçiminə təsir edən maraqlarını, qabiliyyətini və dəyərlərini bir yerə yığır.',
 niye:'Seçim çox vaxt valideyn istəyi və ya ətraf təsiri ilə edilir. Test yeniyetmənin öz meyli ilə real imkanları arasındakı uyğunluğu göstərir.',
 terkib:['Maraqlar modulu (RIASEC)','Qabiliyyət və idrak modulu','Şəxsiyyət və dəyərlər modulu','İki dildə (Azərbaycan və rus) keçirilir'],
 netice:['Qaydaya əsaslanan ətraflı hesabat (süni intellektsiz)','Hesabat çap edilib valideynə verilə bilər','Link uşağa göndərilir, lakin nəticə yalnız psixoloq panelində PIN ilə görünür'],
 mehdud:'Normal inkişaf edən yeniyetmələr üçündür. Test peşə seçimi üçün istiqamət verir, qərarı əvəz etmir.',
 linkler:[{t:'Aləti aç',u:U.ixtisas}]}
];

const KURSLAR=[
{id:'kurs-portali',ad:'AN Kurs Portalı',alt:'Mərkəzin kurs qeydiyyat və tədris platforması',tip:'Platforma',
 hedef:'Psixoloqlar, loqopedlər, ergoterapevtlər və psixopedaqoqlar',
 ne:'Mərkəzin peşəkar kurslarına qeydiyyat, tədris materialları və sertifikat prosesi bir yerdə cəmlənir.',
 terkib:['Kurs qeydiyyatı və idarəetmə paneli','Azərbaycan, ingilis, rus və türk dillərində interfeys','Kursu bitirənlərə rəsmi sertifikat','Praktik və klinik məzmun'],
 qeyd:'Mərkəz klinik psixoloq Nahidə Axundova tərəfindən qurulub və idarə olunur.',
 linkler:[{t:'Portalı aç',u:'https://samir210-az.github.io/an-kurs-portali/'}]},

{id:'cbt-kursu',ad:'Koqnitiv Davranış Terapiyası Kursu',alt:'Uşaq, yeniyetmə və böyüklər üçün 20 modul',tip:'Peşəkar kurs',
 hedef:'Uşaq, yeniyetmə və böyüklərlə işləyən mütəxəssislər',
 ne:'Klinik əsaslı, seans-seans strukturlaşdırılmış CBT proqramı: nəzəriyyədən praktik iş dəftərlərinə qədər.',
 terkib:['20 modul','125-dən çox CBT texnikası','Əsas model: düşüncə, davranış və hiss üçbucağı','Uşaq, yeniyetmə və böyüklər üçün ayrı istiqamətlər'],
 qeyd:'',
 linkler:[{t:'Kursu aç',u:'https://samir210-az.github.io/koqnitiv_kurs/'}]},

{id:'usaq-psixologiya',ad:'Uşaq və Yeniyetmə Psixologiyası Kursu',alt:'15 tam proqram, 250-dən çox seans',tip:'Peşəkar kurs',
 hedef:'Psixoloji dəstək və reabilitasiya sahəsində çalışan mütəxəssislər',
 ne:'Erkən diaqnostikadan autizm, DEHB, davranış, nitq və emosional pozuntularla işə qədər klinik əsaslı psixoloji müdaxilə.',
 terkib:['15 tam proqram','250-dən çox seans','5 mütəxəssis baxışı','Hər proqram seans-seans strukturlaşdırılıb'],
 qeyd:'',
 linkler:[{t:'Kursu aç',u:'https://samir210-az.github.io/usaq-psixologiyasi-kursu/'}]},

{id:'terapiya-programlari',ad:'Uşaq və Yeniyetmə Terapiya Proqramları',alt:'13 proqram, 150-dən çox seans',tip:'Peşəkar kurs',
 hedef:'Uşaq və yeniyetmələrlə terapevtik işləyən mütəxəssislər',
 ne:'Aqressivlikdən kəkələməyə, oyun terapiyasından qrup modelinə qədər klinik əsaslı proqramlar.',
 terkib:['13 proqram','150-dən çox seans','5 mütəxəssis baxışı','Aqressivlik, kəkələmə, oyun terapiyası və qrup modeli kimi mövzular'],
 qeyd:'',
 linkler:[{t:'Kursu aç',u:'https://samir210-az.github.io/kurs_13/'}]},

{id:'valideyn-akademiyasi',ad:'AN Valideyn Akademiyası',alt:'12 həftəlik onlayn təlim',tip:'Valideynlər üçün',
 hedef:'Autizm, DEHB, nitq gecikməsi, davranış çətinlikləri və Daun sindromu olan uşaqların valideynləri',
 ne:'Valideynə uşağı ilə evdə sistemli işləməyi öyrədən onlayn təlim platforması.',
 terkib:['12 həftəlik proqram, 6 modul','Tanışlıq və müşahidə (1–2-ci həftə)','Ünsiyyət bacarıqları (3–4)','Davranış idarəetməsi (5–6)','Sensor dəstək (7–8)','Sosial inkişaf (9–10)','Müstəqillik və nəticə (11–12)'],
 qeyd:'Azərbaycan, Rusiya, Qazaxıstan, Özbəkistan və Türkiyədən valideynləri hədəfləyir.',
 linkler:[{t:'Akademiyanı aç',u:'https://an-valideyn-akademiyasi.vercel.app/'}]},

{id:'mektebe-hazirliq',ad:'AN Məktəbə Hazırlıq',alt:'5–6 yaş üçün 8 həftəlik proqram',tip:'Uşaq proqramı',
 hedef:'5–6 yaşlı uşaqlar və valideynlər',
 ne:'Məktəbə zehni, emosional və sosial hazırlığı birlikdə təmin edən proqram.',
 terkib:['8 həftə','6 fənn, o cümlədən 3 dil','Gündəlik davranış və bilik qiymətləndirməsi (1–5 şkalası)','Əlifba və rəqəm bölmələri','Valideyn üçün hesabat'],
 qeyd:'',
 linkler:[{t:'Proqramı aç',u:'https://samir210-az.github.io/mektebe-hazirlik/'}]}
];

const KOMEKCI=[
{id:'sesim',ad:'Səsim',alt:'Piktoqram əsaslı alternativ ünsiyyət tətbiqi',tip:'Tətbiq',
 hedef:'Nitqi məhdud olan və ya nitqi olmayan şəxslər, ailələri, loqopedlər',
 ne:'Şəkil kartları vasitəsilə istəyini bildirməyə kömək edən ünsiyyət tətbiqi.',
 terkib:['ARASAAC peşəkar piktoqramları, istəyə görə emoji','Azərbaycan, rus və ingilis dilləri','Mətnin səsləndirilməsi','Valideyn rejimi: kartları idarə etmək və yenisini yaratmaq'],
 qeyd:'',
 linkler:[{t:'Tətbiqi aç',u:'https://samir210-az.github.io/sesim/'}]},

{id:'ferdi-plan',ad:'Fərdi Reabilitasiya Planı',alt:'Qayda əsaslı plan generatoru',tip:'Mütəxəssis aləti',
 hedef:'Mərkəzin mütəxəssisləri',
 ne:'Uşağın qiymətləndirmə nəticələrinə uyğun fərdi reabilitasiya planı hazırlayır.',
 terkib:['Qaydalara əsaslanır, süni intellekt işlətmir','Valideynlər üçün ayrıca bələdçi versiyası var'],
 qeyd:'',
 linkler:[{t:'Planı aç',u:'https://samir210-az.github.io/plan/'},{t:'Valideyn bələdçisi',u:'https://samir210-az.github.io/plan-valideyn/'}]}
];
